# NumPy 教程

NumPy 的核心是多维数组，具有快速、方便、内存占用低等优点，在数据处理领域的应用太不能再广泛了。

## 1. 快速参考

In [1]:
import numpy as np

### 1.1 基本概念
- 数组的维度称为 axes
- axes 的数值称为 rank
- NumPy 内部以 **`ndarray`** 对象表示数组



### 1.2 ndarray 属性

## 2. 创建数组

In [2]:
# 通过 list 创建 ndarray
a = np.array([2, 23, 4])
a

array([ 2, 23,  4])

In [3]:
# 创建时指定数据类型
a = np.array([2, 3, 4], dtype=np.float32)
a

array([ 2.,  3.,  4.], dtype=float32)

In [4]:
# 创建二维数组
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 创建全部为0的矩阵，创建时指定 shape,如3行4列
a = np.zeros((3, 4))
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
# 创建全部为 1 的矩阵
a = np.ones((3, 4))
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [7]:
a = np.empty((3, 4))
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
# reshape() 重新定义 shape
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# 在 [1,10] 之间，生成20个等差数值
a = np.linspace(1, 10, 20)
a

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

## 3. 基本运算

In [11]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.arange(4)

In [12]:
# 加法，各个元素分别相加，如果长度不等，报错
c = a+b
c

array([10, 21, 32, 43])

In [13]:
b = np.arange(3)
c = a+b
c

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

# 参考资料
- http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html
- https://github.com/jrjohansson/scientific-python-lectures
- https://docs.scipy.org/doc/numpy/reference/
- [https://docs.scipy.org/doc/numpy-dev/user/quickstart.html](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)